package domain/*
 * domain.Toolchain.kt
 *
 * This code was generated by json-kotlin-schema-codegen - JSON Schema Code Generator
 * See https://github.com/pwall567/json-kotlin-schema-codegen
 *
 * It is not advisable to modify generated code as any modifications will be lost
 * when the generation process is re-run.
 */

import kotlinx.serialization.Serializable
import kotlinx.serialization.Transient

@Serializable
data class Toolchain(
    val name: String,
    val description: String? = null,
    private val params: Map<String, String>? = null,
    val paramDefaults: Map<String, String>? = null,
    val action: String,
    val children: Array<Toolchain>? = null
) {
    @Transient
    val parsedParameters: Array<Parameter> = params.orEmpty().map { (name, definition) ->
        require(ParamNameRegex.matches(name)) {
            "Param name does not match the pattern $ParamNameRegex - $name"
        }
        val match = ParamDefinitionRegex.find(definition)
        requireNotNull(match) { "Param definition does not match pattern $ParamDefinitionRegex - $definition" }
        Parameter(
            name = name,
            optional = when (match.groupValues[1]) {
                "req" -> false
                "opt" -> true
                else -> throw Exception()
            },
            shorthand = match.groups[3]?.value,
            type = when (match.groupValues[2]) {
                "flag" -> Type.Flag
                "arg" -> Type.Arg
                else -> throw Exception()
            },
            description = match.groups[4]?.value
        )
    }.toTypedArray()

    enum class Type {
        Flag,
        Arg
    }

    companion object {
        private val ParamDefinitionRegex = Regex("^(req|opt):(flag|arg)(:\\w)?(?:: *(.*))?\$")
        private val ParamNameRegex = Regex("\\w+")
    }
}
