package domain/*
 * domain.Toolchain.kt
 *
 * This code was generated by json-kotlin-schema-codegen - JSON Schema Code Generator
 * See https://github.com/pwall567/json-kotlin-schema-codegen
 *
 * It is not advisable to modify generated code as any modifications will be lost
 * when the generation process is re-run.
 */

import emptyString
import isJsonObject
import isString
import kotlinx.serialization.Serializable
import kotlinx.serialization.Transient
import kotlinx.serialization.json.JsonElement
import kotlinx.serialization.json.contentOrNull
import kotlinx.serialization.json.jsonObject
import kotlinx.serialization.json.jsonPrimitive
import kotlin.js.ExperimentalJsExport
import kotlin.js.JsExport

@OptIn(ExperimentalJsExport::class, ExperimentalJsExport::class)
@Serializable
@JsExport
data class Toolchain(
    val name: String,
    val description: String? = null,
    val paramDefaults: Map<String, String>? = null,
    private val parameters: Array<String>? = null,
    private val action: JsonElement?,
    val children: Array<Toolchain>? = null
) {
    @Transient
    val parsedParameters: Array<Parameter> = parameters.orEmpty().map {
        val match = ParameterRegex.find(it)
        requireNotNull(match) { "parameters item does not match pattern $ParameterRegex - $it" }
        Parameter(
            name = match.groupValues[3],
            optional = when (match.groupValues[1]) {
                "req" -> false
                "opt" -> true
                else -> throw Exception()
            },
            shorthand = match.groups[4]?.value,
            type = when (match.groupValues[2]) {
                "flag" -> Type.Flag
                "arg" -> Type.Arg
                else -> throw Exception()
            },
            description = match.groups[5]?.value
        )
    }.toTypedArray()

    @Transient
    val parsedAction = action?.jsonPrimitive?.contentOrNull ?:
        action?.jsonObject?.get("template")?.jsonPrimitive?.content ?:
        emptyString()

    init {
        require(action == null ||
                action.jsonPrimitive.isString ||
                action.isJsonObject && ("template" !in action.jsonObject || action.jsonObject["template"]!!.isString))
        {
            "`action` must be either a string or an object containing a `template` property which is string"
        }
    }

    enum class Type {
        Flag,
        Arg
    }

    companion object {
        private val ParameterRegex = Regex("^(req|opt):(flag|arg):(\\w+)(:\\w)?(?:: *(.*))?\$")
    }
}
